### ISSUE TITLE
Sometimes rtv not executing

### ISSUE THREAD

**Issue by xpara97** [PhantomYopta/LiteMapChooser#1]
Sometimes a succesful rtv vote is not executing. We get the message which confirms the mapchange and the succesful rtv vote, but its not changing in rare cases.

Could not figure out the exact reason. Happened with 2 players. Maybe regarding to not reaching the required 0.6 ? Will do more testing and update this issue.

OS: Ubuntu 22.04, CS2 Dedi run in docker container

**Comment by PhantomYopta** [comment]
I'll post the fix tomorrow

**Comment by xpara97** [comment]
Fix with new cvar in readme?

**Comment by jovicdev97** [comment]
Thanks for fix!!
