### ISSUE TITLE
dont work anymore

### ISSUE THREAD

**Issue by S3ri0uS90** [PhantomYopta/LiteMapChooser#3]
rtv plugin doesnt work anymore.

rtv plugin configurated with ws: fy_pool_day in maps.txt eg.

**Comment by Julienhqr** [comment]
Hi me too,

Do you need to download the map file and place it into server game folder (/game/maps/ ) or we need just to write the map name in maps.txt ?

Cause with basic maps it works but nothing with ws:mapname

**Comment by S3ri0uS90** [comment]
before sharp update it worked for standard maps. Then i decided to put in :ws like in mapfile.txt described. No functionality anymore i think. It displays the maps you can choose but dooesnt work. I added the collection in the startparameters all maps downloaded on server.... and the location is cs2/game/bin/linuxsteamrt64/steamapps/workshop/content.....

**Comment by S3ri0uS90** [comment]
I figgured it out , THIS PLUGIN WORKS fine.  Just host your server with :
host_workshop_collection YOUR-COLLECTION-ID -authkey YOUR-AUTH-KEY <----Steam api
Set the profile setting of your own collectionprofile to public if its set to private.
edit                    maps.txt 
restart  your server. done

path for workshop maps at linux : cs2/game/bin/linuxsteamrt64/steamapps/workshop/content/730
